- name: Preparar la aplicación para deployment
  hosts: localhost
  vars:
    repo_url: https://github.com/spring-guides/gs-spring-boot.git
    workspace: ~/src/helloworld

  tasks:
  - name: Git Clone el app de demonstración
    git:
      repo: "{{ repo_url }}"
      dest: "{{ workspace }}"
  
  - name: Build sample app
    shell: mvn package chdir="{{ workspace }}/complete"

- name: Importar los demás playbooks...
  import_playbook: vmss-setup-deploy.yml 
