- name: Obtener información de nuestro grupo de recursos
  hosts: localhost
  tasks:
    - name: Incluir el archivo de variables
      include_vars:
        file: variables.yml

    - name: Recopilando información de VMSS...
      azure_rm_virtualmachinescaleset_info:
        name: "{{ vmss_name }}"
        resource_group: "{{ resource_group }}"
      register: resultado
    
    - name: Viendo resultado...
      debug:
        msg: "{{ resultado['vmss'][0]['sku']['capacity'] }}"
