- name: Conseguiendo información inicial
  hosts: localhost
  tasks:
    - name: Incluir archivo variables
      include_vars:
        file: variables.yml

- name: Include a play after another play
  import_playbook: get-hosts-tasks.yml

- name: Setting up SSH and stress modules
  hosts: scalesethosts
  become: yes
  vars:
    admin_username: azureuser

  tasks:
    - name: Install SSH
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - ssh
        - stress
        - git

    - name: Stress CPU over 50%
      shell: stress --cpu 1 --timeout 900
