- name: Setup completo del VM con la aplicación base
  hosts: localhost
  tasks:
    - name: Incluir variables
      include_vars:
        file: variables.yml

    - name: Creando VM...
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_testing_name }}"
        vm_size: "{{ vm_size_option }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ vmss_password }}"
        ssh_password_enabled: True
        managed_disk_type: Standard_LRS
        os_disk_caching: ReadWrite
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: "{{ sku_var }}"
          version: latest

- name: Importando el playbook para hacer deploy el app...
  import_playbook: vm_setup.yml
