- name: Retrieve info of virtual machine
  hosts: localhost
  tasks:
    - name: Incluir el archivo de variables
      include_vars:
        file: variables.yml

    - name: Getting VM info...
      azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group }}"
      register: resultado

    - name: Revisando resultado...
      debug:
        msg: "{{ resultado }}"
