---
- name: Conseguiendo información inicial
  hosts: localhost
  tasks:
    - name: Incluir archivo variables
      include_vars:
        file: variables.yml

- name: Include a play after another play
  import_playbook: get-hosts-tasks.yml

- name: Setting up SSH and stress modules
  hosts: scalesethosts
  tasks:
    - name: Install SSH
      package:
        name: ssh
        state: present
...
