- name: Preparar la aplicación para deployment
  hosts: localhost
  vars:
    repo_url: https://github.com/Spring-Boot-Framework/Spring-Boot-Application-Template.git 
    workspace: ~/src/project2

  tasks:
  - name: Git Clone el app de demonstración
    git:
      repo: "{{ repo_url }}"
      dest: "{{ workspace }}"

  - name: Build sample app
    shell: mvn package chdir="{{ workspace }}/"

- name: Importar los demás playbooks...
  import_playbook: sample-app-setup-deploy.yml 
