- name: Preparar la aplicaci칩n para deployment
  hosts: localhost
  vars:
    repo_url: https://github.com/Spring-Boot-Framework/Spring-Boot-Application-Template.git 
    workspace: ~/src/project2

  tasks:
  - name: Git Clone el app de demonstraci칩n
    git:
      repo: "{{ repo_url }}"
      dest: "{{ workspace }}"

  - name: Build sample app
    shell: mvn package chdir="{{ workspace }}/"

- name: Importar playbook para la creaci칩n de un testing VM...
  import_playbook: create_vm.yml

- name: Importar los dem치s playbooks...
  import_playbook: sample-app-setup-deploy.yml 
