- name: Conseguiendo información inicial
  hosts: localhost
  tasks:
    - name: Incluir archivo variables
      include_vars:
        file: variables.yml

- name: Include a play after another play
  import_playbook: get-hosts-tasks.yml

- name: Install JRE on a scale set
  hosts: scalesethosts
  become: yes
  vars:
    workspace: ~/src/project2
    admin_username: azureuser

  tasks:
    - name: Install JRE
      apt:
        name: default-jre
        update_cache: yes
  
    - name: Instalar MySQL
      package:
        name: msyql
        state: present

    - name: Iniciar el servicio de MySQL
      service:
        name: mysql
        state: started

    - name: Crear la base de datos
      mysql_db:
        name: sbat
        state: present

    - name: Crear el usuario de la base de datos
      mysql_user:
        name: sbat
        state: present
        plugin: sbat
        priv: '*.*:ALL,GRANT'

    - name: Copy app to Azure VM
      copy:
        src: "{{ workspace }}/target/spring-boot-application-template-latest.jar"
        dest: "/home/{{ admin_username }}/sample.jar"
        force: yes
        mode: 0755
  
    - name: Start the application
      shell: java -jar "/home/{{ admin_username }}/sample.jar" >/dev/null 2>&1 &
      async: 5000
      poll: 0
