- hosts: localhost
  tasks:
    - name: Incluir el archivo de variables
      include_vars:
        file: vars/variables.yml
    - name: Create a scale set
      azure_rm_virtualmachinescaleset:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        vm_size: Standard_DS1_v2
        admin_username: "{{ admin_username }}"
        admin_password: "{{ vmss_password }}"
        ssh_password_enabled: True
        capacity: 2
        virtual_network_name: "{{ vmss_name }}"
        subnet_name: "{{ vmss_name }}"
        upgrade_policy: Manual
        tier: Standard
        managed_disk_type: Standard_LRS
        os_disk_caching: ReadWrite
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest
          resource_group: "{{ resource_group }}"
        load_balancer: "{{ vmss_name }}lb"
