- name: Actualizar datos del VMSS
  hosts: localhost
  tasks:
    - name: Incluir archivo de variables
      include_vars:
        file: variables.yml

    - name: Actualizando imagen del VMSS...
      azure_rm_virtualmachinescaleset:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        vm_size: "{{ vm_size_option }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ vmss_password }}"
        ssh_password_enabled: True
        capacity: "{{ vm_capacity }}"
        virtual_network_name: "{{ vmss_name }}"
        subnet_name: "{{ vmss_name }}"
        upgrade_policy: "{{ policy_var }}"
        tier: Standard
        managed_disk_type: Standard_LRS
        os_disk_caching: ReadWrite
        image:
          name: "{{ custom_image_name }}"
          resource_group: "{{ resource_group }}"
        load_balancer: "{{ vmss_name }}lb"

- name: Importando playbook para recopilar info de nuevos hosts...
  import_playbook: get-hosts-tasks.yml

- name: Correr la aplicación
  hosts: scalesethosts
  become: yes
  tasks:
    - name: Iniciar la aplicación...
      shell: java -jar "/home/{{ admin_username }}/sample.jar" >/dev/null 2>&1 &
      async: 5000
      poll: 0
